services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: video_service
      REDIS_URL: redis://redis:6379/0
    volumes:
      - video_storage:/app/storage
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-worker
    command: celery -A app.config.celery_app.celery_app worker --loglevel=info --concurrency=1 --prefetch-multiplier=1 --max-tasks-per-child=10
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: video_service
      REDIS_URL: redis://redis:6379/0
    volumes:
      - video_storage:/app/storage
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: video-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: video-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: video-mongo-express
    profiles:
      - dev
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo_data:
  video_storage: